version: '3'
services:
  spring-boot-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/usergrocery?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3307:3306"
    networks:
      - mynetwork  
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

  
networks:
  mynetwork:
    

